module.exports = {
  developerSidebar: {
    "Get Started": [
      "get-started/overview",
      "get-started/choose-your-path",
      {
        type: "category",
        label: "Development Environment",
        items: [
          {
            type: "category",
            label: "Running Cardano Node",
            link: {
              type: "doc",
              id: "operate-a-stake-pool/node-operations/cardano-components"
            },
            items: [
              "operate-a-stake-pool/node-operations/installing-cardano-node",
              "operate-a-stake-pool/node-operations/running-cardano",
              "operate-a-stake-pool/node-operations/dynamic-block-forging",
              "operate-a-stake-pool/node-operations/rts-options-node",
              "operate-a-stake-pool/node-operations/topology",
              {
                type: "category",
                label: "New Tracing System",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "operate-a-stake-pool/node-operations/new-tracing-system",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Testnets",
            link: {
              type: "doc",
              id: "get-started/testnets-and-devnets"
            },
            items: [
              "integrate-cardano/testnet-faucet",
            ],
          },
          {
            type: "category",
            label: "Local Development Networks",
            items: [
              "get-started/yaci-devkit",
              "get-started/cardano-testnet",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Cardano CLI",
        items: [
          {
            type: "category",
            label: "Basic Operations",
            link: {
              type: "doc",
              id: "get-started/cardano-cli/basic-operations/get-started"
            },
            items: [
              {
                type: "autogenerated",
                dirName: "get-started/cardano-cli/basic-operations",
              },
            ],
          },
          "get-started/cardano-cli/simple-scripts/simple-scripts",
          "get-started/cardano-cli/native-assets/native-assets",
          "get-started/cardano-cli/plutus-scripts/plutus-scripts",
          {
            type: "category",
            label: "Governance",
            items: [
              {
                type: "autogenerated",
                dirName: "get-started/cardano-cli/governance",
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "SDKs",
        link: {
          type: "doc",
          id: "get-started/high-level-sdks-overview"
        },
        items: [
          {
            type: "category",
            label: "Mesh (Web3 SDK)",
            items: [
              {
                type: "autogenerated",
                dirName: "get-started/mesh",
              },
            ],
          },
          {
            type: "category",
            label: "Evolution SDK",
            items: [
              {
                type: "autogenerated",
                dirName: "get-started/evolution-sdk",
              },
            ],
          },
          "get-started/pycardano",
          "get-started/cardanosharp-wallet",
        ],
      },
      {
        type: "category",
        label: "Providers",
        link: {
          type: "doc",
          id: "get-started/providers-overview"
        },
        items: [
          {
            type: "category",
            label: "Blockfrost",
            items: [
              {
                type: "autogenerated",
                dirName: "get-started/blockfrost",
              },
            ],
          },
          "get-started/koios",
          "get-started/ogmios",
        ],
      },
    ],
    "Learn": [
      {
        type: "category",
        label: "Core Concepts",
        link: {
          type: "doc",
          id: "get-started/technical-concepts/overview"
        },
        items: [
          "get-started/technical-concepts/core-blockchain-fundamentals",
          "get-started/technical-concepts/wallet-key-management",
          "get-started/technical-concepts/assets",
          "get-started/technical-concepts/network-communication",
          {
            type: "category",
            label: "Security Best Practices",
            items: [
              "get-started/security/air-gap",
              "get-started/security/secure-workflow",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Educational Resources",
        items: [
          {
            type: "category",
            label: "Haskell",
            items: [
              "get-started/haskell/onboarding",
              "get-started/haskell/functional-programming",
              "get-started/haskell/advanced-functional-programming",
            ],
          },
        ],
      },
    ],
    "Build": [
      {
        type: "category",
        label: "Integration",
        link: {
          type: "doc",
          id: "integrate-cardano/overview"
        },
        items: [
          {
            type: "category",
            label: "Low-Level Tools",
            items: [
              {
                type: "category",
                label: "cardano-wallet",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/cardano-wallet",
                  },
                  "get-started/cardano-wallet-js",
                ],
              },
              {
                type: "category",
                label: "cardano-serialization-lib",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/cardano-serialization-lib",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Wallet Integration",
            items: [
              {
                type: "category",
                label: "User Wallet Authentication",
                link: {
                  type: "doc",
                  id: "integrate-cardano/user-wallet-authentication/overview"
                },
                items: [
                  "integrate-cardano/user-wallet-authentication/mesh",
                  "integrate-cardano/user-wallet-authentication/cardano-serialization-lib",
                ],
              },
              "integrate-cardano/multi-witness-transactions-cli",
            ],
          },
          {
            type: "category",
            label: "Payment Integration",
            items: [
              {
                type: "category",
                label: "Listening for Payments",
                link: {
                  type: "doc",
                  id: "integrate-cardano/listening-for-payments/overview"
                },
                items: [
                  "integrate-cardano/listening-for-payments/point-of-sale",
                  "integrate-cardano/listening-for-payments/cardano-cli",
                  "integrate-cardano/listening-for-payments/cardano-wallet",
                ],
              },
              "integrate-cardano/exchange-integrations",
              "integrate-cardano/creating-wallet-faucet",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Smart Contracts",
        link: {
          type: "doc",
          id: "smart-contracts/overview"
        },
        items: [
          {
            type: "category",
            label: "Smart Contract Languages",
            items: [
              {
                type: "category",
                label: "Aiken",
                items: [
                  "smart-contracts/smart-contract-languages/aiken/overview",
                  "smart-contracts/smart-contract-languages/aiken/smart-contract-library",
                  {
                    type: "category",
                    label: "Advanced Data Structures",
                    items: [
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/linked-list",
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/merkle-tree",
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/trie",
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Plutarch",
                items: [
                  "smart-contracts/smart-contract-languages/plutarch/overview",
                  {
                    type: "category",
                    label: "Advanced Data Structures",
                    items: [
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/linked-list",
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/merkle-tree",
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/trie",
                    ],
                  },
                  {
                    type: "category",
                    label: "Production Grade DApps",
                    items: [
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/overview",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/nix-environments",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/bridge-template",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/linear-vesting",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/merkle-tree",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/yield-farming",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/single-asset-staking",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/smart-handles",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/direct-offer",
                    ],
                  },
                ],
              },
              "smart-contracts/smart-contract-languages/plinth",
              "smart-contracts/smart-contract-languages/opshin",
              "smart-contracts/smart-contract-languages/plu-ts",
              "smart-contracts/smart-contract-languages/scalus",
              "smart-contracts/smart-contract-languages/marlowe",
            ],
          },
          {
            type: "category",
            label: "Lessons",
            items: [
              {
                type: "autogenerated",
                dirName: "smart-contracts/lessons",
              },
            ],
          },
          {
            type: "category",
            label: "Advanced",
            items: [
              "smart-contracts/advanced/uplc",
              "smart-contracts/advanced/debug-cbor",
              {
                type: "category",
                label: "Design Patterns",
                items: [
                  "smart-contracts/advanced/design-patterns/overview",
                  "smart-contracts/advanced/design-patterns/enum-redeemers",
                  "smart-contracts/advanced/design-patterns/parameter-validation",
                  "smart-contracts/advanced/design-patterns/strict-and-checks",
                  "smart-contracts/advanced/design-patterns/utxo-indexers",
                  {
                    type: "category",
                    label: "Normalization Techniques",
                    items: [
                      "smart-contracts/advanced/design-patterns/normalization-techniques/txinfomint-normalization",
                      "smart-contracts/advanced/design-patterns/normalization-techniques/validity-range-normalization",
                    ],
                  },
                  {
                    type: "category",
                    label: "Transaction Level Validation",
                    items: [
                      "smart-contracts/advanced/design-patterns/transaction-level-validation/transaction-level-validation-minting-policy",
                      {
                        type: "category",
                        label: "Stake Validators",
                        items: [
                          "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/stake-validator",
                          "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/withdraw-zero",
                          "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/merkelized-validators",
                          "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/global-state",
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Smart Contract Vulnerabilities",
                items: [
                  "smart-contracts/advanced/smart-contract-vulnerabilities/ctf",
                  {
                    type: "category",
                    label: "Invariant0 Blog Series",
                    items: [
                      "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/1-double-satisfaction",
                      "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/2-trust-no-utxo",
                      "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/3-time-handling",
                      "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/4-token-security",
                    ],
                  },
                  {
                    type: "category",
                    label: "MLabs Common Vulnerabilities",
                    items: [
                      "smart-contracts/advanced/smart-contract-vulnerabilities/mlabs-common-vulnerabilities/overview",
                    ],
                  },
                  {
                    type: "category",
                    label: "Mesh Bad Contracts",
                    items: [
                      "smart-contracts/advanced/smart-contract-vulnerabilities/mesh-bad-contracts/overview",
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Native Tokens",
        link: {
          type: "doc",
          id: "native-tokens/overview"
        },
        items: [
          "native-tokens/minting",
          "native-tokens/minting-nfts",
          "native-tokens/authenticated-products",
          {
            type: "category",
            label: "Token Registry",
            items: [
              {
                type: "autogenerated",
                dirName: "native-tokens/token-registry",
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Transaction Metadata",
        link: {
          type: "doc",
          id: "transaction-metadata/overview"
        },
        items: [
          {
            type: "category",
            label: "Tutorials",
            items: [
              "transaction-metadata/mesh",
              "transaction-metadata/how-to-create-a-metadata-transaction-cli",
              "transaction-metadata/how-to-create-a-metadata-transaction-wallet",
            ],
          },
          "transaction-metadata/retrieving-metadata",
        ],
      },
    ],
    "Community": [
      "get-started/cardano-developer-community",
      "get-started/funding",
      {
        type: "category",
        label: "Contributing to Developer Portal",
        items: [
          "portal-contribute",
          "portal-style-guide",
          {
            type: "link",
            label: "Contributors",
            href: "https://github.com/cardano-foundation/developer-portal/graphs/contributors",
          },
        ],
      },
    ],
  },

  governanceSidebar: {
    "Participate in Governance": [
      "governance/overview",
      {
        type: "category",
        label: "Cardano Governance",
        link: {
          type: "doc",
          id: "governance/cardano-governance/overview"
        },
        items: [
          "governance/cardano-governance/cardano-governance",
          "governance/cardano-governance/governance-actions",
          "governance/cardano-governance/submitting-governance-actions",
          "governance/cardano-governance/constitutional-committee-guide",
        ],
      },
    ],
  },

  networkSidebar: {
    "Operate a Stake Pool": [
      "operate-a-stake-pool/overview",
      {
        type: "category",
        label: "Basics",
        items: [
          {
            type: "doc",
            id: "get-started/technical-concepts/consensus-staking",
            label: "(Re)introduction to Cardano"
          },
          "operate-a-stake-pool/stake-pool-networking",
          "operate-a-stake-pool/hardware-requirements",
          "operate-a-stake-pool/cardano-key-pairs",
        ],
      },
      {
        type: "category",
        label: "Cardano Relay Configuration",
        items: [
          "operate-a-stake-pool/relay-node-configuration",
          "operate-a-stake-pool/monitoring-gLiveView",
          "operate-a-stake-pool/grafana-dashboard-tutorial",
        ],
      },
      {
        type: "category",
        label: "Cardano Block Producer Configuration",
        items: [
          "operate-a-stake-pool/generating-wallet-keys",
          "operate-a-stake-pool/block-producer-keys",
          "operate-a-stake-pool/register-stake-address",
          "operate-a-stake-pool/register-stake-pool",
        ],
      },
      {
        type: "category",
        label: "Deployment Scenarios",
        items: [
          "operate-a-stake-pool/hardening-server",
          "operate-a-stake-pool/improve-grafana-security",
          "operate-a-stake-pool/audit-your-node",
        ],
      },
      {
        type: "category",
        label: "Cardano Governance",
        items: [
          "operate-a-stake-pool/on-chain-polls",
        ],
      },
      {
        type: "category",
        label: "Operator Tools",
        items: [
          "operate-a-stake-pool/guild-ops-suite",
          "get-started/security/frankenwallet",
        ],
      },
    ],
  },
};