module.exports = {
  developerSidebar: {
    "Get Started": [
      "get-started/overview",
      {
        type: "category",
        label: "Networks",
        link: {
          type: "doc",
          id: "get-started/networks-overview"
        },
        items: [
          {
            type: "category",
            label: "Testnets",
            link: {
              type: "doc",
              id: "get-started/testnets-and-devnets"
            },
            items: [
              "integrate-cardano/testnet-faucet",
            ],
          },
          {
            type: "category",
            label: "Development Networks",
            link: {
              type: "doc",
              id: "get-started/development-networks"
            },
            items: [
              "get-started/yaci-devkit",
              "get-started/cardano-testnet",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Infrastructure",
        link: {
          type: "doc",
          id: "get-started/choose-your-approach"
        },
        items: [
          {
            type: "category",
            label: "API Providers",
            link: {
              type: "doc",
              id: "get-started/providers-overview"
            },
            items: [
              {
                type: "category",
                label: "Blockfrost",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/blockfrost",
                  },
                ],
              },
              "get-started/koios",
              "get-started/ogmios",
            ],
          },
          {
            type: "category",
            label: "Cardano Node & Tools",
            items: [
              {
                type: "category",
                label: "Run Your Own Node",
                link: {
                  type: "doc",
                  id: "operate-a-stake-pool/node-operations/cardano-components"
                },
                items: [
                  "operate-a-stake-pool/node-operations/installing-cardano-node",
                  "operate-a-stake-pool/node-operations/running-cardano",
                  "operate-a-stake-pool/node-operations/dynamic-block-forging",
                  "operate-a-stake-pool/node-operations/rts-options-node",
                  "operate-a-stake-pool/node-operations/topology",
                  {
                    type: "category",
                    label: "New Tracing System",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "operate-a-stake-pool/node-operations/new-tracing-system",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "cardano-cli",
                items: [
                  {
                    type: "category",
                    label: "Basic Operations",
                    link: {
                      type: "doc",
                      id: "get-started/cardano-cli/basic-operations/get-started"
                    },
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "get-started/cardano-cli/basic-operations",
                      },
                    ],
                  },
                  "get-started/cardano-cli/multi-witness-transactions",
                  "get-started/security/secure-workflow",
                  "get-started/cardano-cli/simple-scripts/simple-scripts",
                  "get-started/cardano-cli/native-assets/native-assets",
                  "get-started/cardano-cli/plutus-scripts/plutus-scripts",
                  {
                    type: "category",
                    label: "Governance",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "get-started/cardano-cli/governance",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "cardano-wallet",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/cardano-wallet",
                  },
                ],
              },
            ],
          },
          "get-started/demeter",
        ],
      },
      {
        type: "category",
        label: "Client SDKs",
        link: {
          type: "doc",
          id: "get-started/high-level-sdks-overview"
        },
        items: [
          {
            type: "category",
            label: "TypeScript",
            link: {
              type: "doc",
              id: "get-started/typescript-sdks"
            },
            items: [
              {
                type: "category",
                label: "Mesh SDK",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/mesh",
                  },
                ],
              },
              {
                type: "category",
                label: "Evolution SDK",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/evolution-sdk",
                  },
                ],
              },
              {
                type: "category",
                label: "UTXOS Web3 Services",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/utxos",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Python",
            items: [
              "get-started/pycardano",
            ],
          },
          {
            type: "category",
            label: "Rust",
            items: [
              "get-started/client-sdks/rust/pallas",
              "get-started/client-sdks/rust/whisky",
            ],
          },
          {
            type: "category",
            label: "Go",
            items: [
              "get-started/client-sdks/go/apollo",
            ],
          },
          {
            type: "category",
            label: "C#",
            items: [
              "get-started/cardanosharp-wallet",
            ],
          },
          {
            type: "category",
            label: "Swift",
            items: [
              "get-started/client-sdks/swift/cardanokit",
            ],
          },
          {
            type: "category",
            label: "Low-Level",
            items: [
              {
                type: "category",
                label: "Cardano Serialization Library",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/cardano-serialization-lib",
                  },
                ],
              },
              "get-started/client-sdks/low-level/cml",
            ],
          },
        ],
      },
    ],
    "Learn": [
      {
        type: "category",
        label: "Core Concepts",
        link: {
          type: "doc",
          id: "get-started/technical-concepts/overview"
        },
        items: [
          "get-started/technical-concepts/eutxo",
          "get-started/technical-concepts/transactions",
          "get-started/technical-concepts/addresses",
          "get-started/technical-concepts/fees",
          "get-started/technical-concepts/assets",
        ],
      },
      {
        type: "category",
        label: "Educational Resources",
        items: [
          "get-started/security/air-gap",
          {
            type: "category",
            label: "Haskell",
            items: [
              "get-started/haskell/onboarding",
              "get-started/haskell/functional-programming",
              "get-started/haskell/advanced-functional-programming",
            ],
          },
        ],
      },
    ],
    "Build": [
      {
        type: "category",
        label: "Integrate",
        link: {
          type: "doc",
          id: "integrate-cardano/overview"
        },
        items: [
          {
            type: "category",
            label: "Payments",
            items: [
              {
                type: "category",
                label: "Listening for Payments",
                link: {
                  type: "doc",
                  id: "integrate-cardano/listening-for-payments/overview"
                },
                items: [
                  "integrate-cardano/listening-for-payments/point-of-sale",
                  "integrate-cardano/listening-for-payments/cardano-cli",
                  "integrate-cardano/listening-for-payments/cardano-wallet",
                ],
              },
              "integrate-cardano/x402-standard",
            ],
          },
          {
            type: "category",
            label: "User Wallet Authentication",
            link: {
              type: "doc",
              id: "integrate-cardano/user-wallet-authentication/overview"
            },
            items: [
              "integrate-cardano/user-wallet-authentication/mesh",
              "integrate-cardano/user-wallet-authentication/cardano-serialization-lib",
            ],
          },
          {
            type: "category",
            label: "AI Agents",
            link: {
              type: "doc",
              id: "integrate-cardano/ai-agents/overview"
            },
            items: [
              "integrate-cardano/ai-agents/masumi",
            ],
          },
          {
            type: "category",
            label: "Oracles",
            link: {
              type: "doc",
              id: "integrate-cardano/oracles-overview"
            },
            items: [
              "integrate-cardano/charli3",
              "integrate-cardano/orcfax",
            ],
          },
          "integrate-cardano/exchange-integrations",
        ],
      },
      {
        type: "category",
        label: "Native Tokens",
        link: {
          type: "doc",
          id: "native-tokens/overview"
        },
        items: [
          "native-tokens/minting",
          "native-tokens/minting-nfts",
          "native-tokens/authenticated-products",
          {
            type: "category",
            label: "Token Registry",
            items: [
              {
                type: "autogenerated",
                dirName: "native-tokens/token-registry",
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Transaction Metadata",
        link: {
          type: "doc",
          id: "transaction-metadata/overview"
        },
        items: [
          {
            type: "category",
            label: "Tutorials",
            items: [
              "transaction-metadata/mesh",
              "transaction-metadata/how-to-create-a-metadata-transaction-cli",
              "transaction-metadata/how-to-create-a-metadata-transaction-wallet",
            ],
          },
          "transaction-metadata/retrieving-metadata",
        ],
      },
      {
        type: "category",
        label: "Smart Contracts",
        link: {
          type: "doc",
          id: "smart-contracts/overview"
        },
        items: [
          {
            type: "category",
            label: "Languages",
            items: [
              {
                type: "category",
                label: "Aiken",
                link: {
                  type: "doc",
                  id: "smart-contracts/smart-contract-languages/aiken/overview"
                },
                items: [
                  "smart-contracts/smart-contract-languages/aiken/smart-contract-library",
                  {
                    type: "category",
                    label: "Advanced Data Structures",
                    items: [
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/linked-list",
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/merkle-tree",
                      "smart-contracts/smart-contract-languages/aiken/advanced-data-structures/trie",
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Plutarch",
                link: {
                  type: "doc",
                  id: "smart-contracts/smart-contract-languages/plutarch/overview"
                },
                items: [
                  {
                    type: "category",
                    label: "Advanced Data Structures",
                    items: [
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/linked-list",
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/merkle-tree",
                      "smart-contracts/smart-contract-languages/plutarch/advanced-data-structures/trie",
                    ],
                  },
                  {
                    type: "category",
                    label: "Production Grade DApps",
                    items: [
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/overview",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/nix-environments",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/bridge-template",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/linear-vesting",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/merkle-tree",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/yield-farming",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/single-asset-staking",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/smart-handles",
                      "smart-contracts/smart-contract-languages/plutarch/production-grade-dapps/direct-offer",
                    ],
                  },
                ],
              },
              "smart-contracts/smart-contract-languages/plinth",
              "smart-contracts/smart-contract-languages/opshin",
              "smart-contracts/smart-contract-languages/plu-ts",
              "smart-contracts/smart-contract-languages/scalus",
              "smart-contracts/smart-contract-languages/marlowe",
            ],
          },
          {
            type: "category",
            label: "Design Patterns",
            link: {
              type: "doc",
              id: "smart-contracts/advanced/design-patterns/overview"
            },
            items: [
              "smart-contracts/advanced/design-patterns/enum-redeemers",
              "smart-contracts/advanced/design-patterns/parameter-validation",
              "smart-contracts/advanced/design-patterns/strict-and-checks",
              "smart-contracts/advanced/design-patterns/utxo-indexers",
              {
                type: "category",
                label: "Normalization Techniques",
                items: [
                  "smart-contracts/advanced/design-patterns/normalization-techniques/txinfomint-normalization",
                  "smart-contracts/advanced/design-patterns/normalization-techniques/validity-range-normalization",
                ],
              },
              {
                type: "category",
                label: "Transaction Level Validation",
                items: [
                  "smart-contracts/advanced/design-patterns/transaction-level-validation/transaction-level-validation-minting-policy",
                  {
                    type: "category",
                    label: "Stake Validators",
                    items: [
                      "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/stake-validator",
                      "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/withdraw-zero",
                      "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/merkelized-validators",
                      "smart-contracts/advanced/design-patterns/transaction-level-validation/stake-validators/global-state",
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Smart Contract Security",
            items: [
              "smart-contracts/advanced/smart-contract-vulnerabilities/ctf",
              {
                type: "category",
                label: "Invariant0 Blog Series",
                items: [
                  "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/1-double-satisfaction",
                  "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/2-trust-no-utxo",
                  "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/3-time-handling",
                  "smart-contracts/advanced/smart-contract-vulnerabilities/invariant0-blog/4-token-security",
                ],
              },
              {
                type: "category",
                label: "MLabs Common Vulnerabilities",
                items: [
                  "smart-contracts/advanced/smart-contract-vulnerabilities/mlabs-common-vulnerabilities/overview",
                ],
              },
              {
                type: "category",
                label: "Mesh Bad Contracts",
                items: [
                  "smart-contracts/advanced/smart-contract-vulnerabilities/mesh-bad-contracts/overview",
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Advanced",
            items: [
              "smart-contracts/advanced/uplc",
              "smart-contracts/advanced/debug-cbor",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Lessons",
        link: {
          type: "doc",
          id: "smart-contracts/lessons-overview"
        },
        items: [
          {
            type: "autogenerated",
            dirName: "smart-contracts/lessons",
          },
        ],
      },
    ],
    "Community": [
      "get-started/cardano-developer-community",
      "get-started/funding",
      {
        type: "category",
        label: "Contributing to Developer Portal",
        items: [
          "portal-contribute",
          "portal-style-guide",
          {
            type: "link",
            label: "Contributors",
            href: "https://github.com/cardano-foundation/developer-portal/graphs/contributors",
          },
        ],
      },
    ],
  },

  governanceSidebar: {
    "Participate in Governance": [
      "governance/overview",
      {
        type: "category",
        label: "Cardano Governance",
        link: {
          type: "doc",
          id: "governance/cardano-governance/overview"
        },
        items: [
          "governance/cardano-governance/cardano-governance",
          "governance/cardano-governance/governance-actions",
          "governance/cardano-governance/submitting-governance-actions",
          "governance/cardano-governance/constitutional-committee-guide",
        ],
      },
    ],
  },

  networkSidebar: {
    "Operate a Stake Pool": [
      "operate-a-stake-pool/overview",
      {
        type: "category",
        label: "Basics",
        items: [
          "get-started/technical-concepts/consensus-staking",
          "operate-a-stake-pool/stake-pool-networking",
          "operate-a-stake-pool/hardware-requirements",
          "operate-a-stake-pool/cardano-key-pairs",
        ],
      },
      {
        type: "category",
        label: "Cardano Relay Configuration",
        items: [
          "operate-a-stake-pool/relay-node-configuration",
          "operate-a-stake-pool/monitoring-gLiveView",
          "operate-a-stake-pool/grafana-dashboard-tutorial",
        ],
      },
      {
        type: "category",
        label: "Cardano Block Producer Configuration",
        items: [
          "operate-a-stake-pool/generating-wallet-keys",
          "operate-a-stake-pool/block-producer-keys",
          "operate-a-stake-pool/register-stake-address",
          "operate-a-stake-pool/register-stake-pool",
        ],
      },
      {
        type: "category",
        label: "Deployment Scenarios",
        items: [
          "operate-a-stake-pool/hardening-server",
          "operate-a-stake-pool/improve-grafana-security",
          "operate-a-stake-pool/audit-your-node",
        ],
      },
      {
        type: "category",
        label: "Cardano Governance",
        items: [
          "operate-a-stake-pool/on-chain-polls",
        ],
      },
      {
        type: "category",
        label: "Operator Tools",
        items: [
          "operate-a-stake-pool/guild-ops-suite",
          "get-started/security/frankenwallet",
        ],
      },
    ],
  },
};