module.exports = {
  developerSidebar: [
    {
      type: "category",
      label: "Get Started",
      link: {
        type: "doc",
        id: "get-started/overview",
      },
      items: [
      {
        type: "category",
        label: "Networks",
        link: {
          type: "doc",
          id: "get-started/networks/overview",
        },
        items: [
          "get-started/networks/testnets",
          {
            type: "category",
            label: "Development Networks",
            link: {
              type: "doc",
              id: "get-started/networks/development-networks/overview",
            },
            items: [
              "get-started/networks/development-networks/yaci-devkit",
              "get-started/networks/development-networks/cardano-testnet",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Infrastructure",
        link: {
          type: "doc",
          id: "get-started/infrastructure/overview",
        },
        items: [
          {
            type: "category",
            label: "API Providers",
            link: {
              type: "doc",
              id: "get-started/infrastructure/api-providers/overview",
            },
            items: [
              {
                type: "category",
                label: "Blockfrost",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/infrastructure/api-providers/blockfrost",
                  },
                ],
              },
              "get-started/infrastructure/api-providers/koios",
              "get-started/infrastructure/api-providers/ogmios",
            ],
          },
          {
            type: "category",
            label: "Cardano Node & Tools",
            items: [
              {
                type: "category",
                label: "Run Your Own Node",
                items: [
                  "get-started/infrastructure/node/cardano-components",
                  "get-started/infrastructure/node/installing-cardano-node",
                  "get-started/infrastructure/node/running-cardano",
                  "get-started/infrastructure/node/dynamic-block-forging",
                  "get-started/infrastructure/node/rts-options-node",
                  "get-started/infrastructure/node/topology",
                  {
                    type: "category",
                    label: "New Tracing System",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "get-started/infrastructure/node/new-tracing-system",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "cardano-cli",
                items: [
                  {
                    type: "category",
                    label: "Basic Operations",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "get-started/infrastructure/cardano-cli/basic-operations",
                      },
                    ],
                  },
                  "get-started/infrastructure/cardano-cli/multi-witness-transactions",
                  "get-started/infrastructure/cardano-cli/security/secure-workflow",
                  "get-started/infrastructure/cardano-cli/simple-scripts/simple-scripts",
                  "get-started/infrastructure/cardano-cli/native-assets/native-assets",
                  "get-started/infrastructure/cardano-cli/plutus-scripts/plutus-scripts",
                  {
                    type: "category",
                    label: "Governance",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "get-started/infrastructure/cardano-cli/governance",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "cardano-wallet",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/infrastructure/cardano-wallet",
                  },
                ],
              },
            ],
          },
          "get-started/infrastructure/demeter",
        ],
      },
      {
        type: "category",
        label: "Client SDKs",
        link: {
          type: "doc",
          id: "get-started/client-sdks/overview",
        },
        items: [
          {
            type: "category",
            label: "TypeScript",

            link: {
              type: "doc",
              id: "get-started/client-sdks/typescript/overview",
            },
            items: [
              {
                type: "category",
                label: "Mesh SDK",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/client-sdks/typescript/mesh",
                  },
                ],
              },
              {
                type: "category",
                label: "Evolution SDK",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/client-sdks/typescript/evolution-sdk",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Python",
            items: [
              "get-started/client-sdks/python/pycardano",
            ],
          },
          {
            type: "category",
            label: "Rust",
            items: [
              "get-started/client-sdks/rust/pallas",
              "get-started/client-sdks/rust/whisky",
            ],
          },
          {
            type: "category",
            label: "Go",
            items: [
              "get-started/client-sdks/go/apollo",
            ],
          },
          {
            type: "category",
            label: "Java",
            items: [
              "get-started/client-sdks/java/cardano-client-lib",
            ],
          },
          {
            type: "category",
            label: "C#",
            items: [
              "get-started/client-sdks/csharp/chrysalis",
            ],
          },
          {
            type: "category",
            label: "Swift",
            items: [
              "get-started/client-sdks/swift/cardanokit",
            ],
          },
          {
            type: "category",
            label: "Low-Level",
            items: [
              {
                type: "category",
                label: "Cardano Serialization Library",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "get-started/client-sdks/low-level/cardano-serialization-lib",
                  },
                ],
              },
              "get-started/client-sdks/low-level/cml",
            ],
          },
        ],
      },
      ],
    },
    {
      type: "category",
      label: "Learn",
      items: [
      {
        type: "category",
        label: "Core Concepts",
        link: {
          type: "doc",
          id: "learn/core-concepts/overview",
        },
        items: [
          "learn/core-concepts/eutxo",
          "learn/core-concepts/transactions",
          "learn/core-concepts/fees",
          "learn/core-concepts/addresses",
          "learn/core-concepts/assets",
        ],
      },
      {
        type: "category",
        label: "Educational Resources",
        items: [
          "learn/educational-resources/ethereum-developers",
          "learn/educational-resources/air-gap",
        ],
      },
      ],
    },
    {
      type: "category",
      label: "Build",
      items: [
      {
        type: "category",
        label: "Smart Contracts",
        link: {
          type: "doc",
          id: "build/smart-contracts/overview",
        },
        items: [
          {
            type: "category",
            label: "Languages",
            items: [
              "build/smart-contracts/languages/aiken/overview",
              {
                type: "category",
                label: "Plutarch (Haskell)",
                link: {
                  type: "doc",
                  id: "build/smart-contracts/languages/plutarch/overview",
                },
                items: [
                  {
                    type: "category",
                    label: "Advanced Data Structures",
                    items: [
                      "build/smart-contracts/languages/plutarch/advanced-data-structures/merkle-tree",
                      "build/smart-contracts/languages/plutarch/advanced-data-structures/trie",
                    ],
                  },
                  {
                    type: "category",
                    label: "Production Grade DApps",
                    link: {
                      type: "doc",
                      id: "build/smart-contracts/languages/plutarch/production-grade-dapps/overview",
                    },
                    items: [
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/nix-environments",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/bridge-template",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/linear-vesting",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/merkle-tree",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/yield-farming",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/single-asset-staking",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/smart-handles",
                      "build/smart-contracts/languages/plutarch/production-grade-dapps/direct-offer",
                    ],
                  },
                ],
              },
              "build/smart-contracts/languages/plinth",
              "build/smart-contracts/languages/opshin",
              "build/smart-contracts/languages/plu-ts",
              "build/smart-contracts/languages/scalus",
              "build/smart-contracts/languages/marlowe",
            ],
          },
          {
            type: "category",
            label: "Design Patterns",
            link: {
              type: "doc",
              id: "build/smart-contracts/advanced/design-patterns/overview",
            },
            items: [
              "build/smart-contracts/advanced/design-patterns/stake-validator",
              "build/smart-contracts/advanced/design-patterns/utxo-indexers",
              "build/smart-contracts/advanced/design-patterns/tx-level-minter",
              "build/smart-contracts/advanced/design-patterns/validity-range-normalization",
              "build/smart-contracts/advanced/design-patterns/merkelized-validator",
              "build/smart-contracts/advanced/design-patterns/parameter-validation",
              "build/smart-contracts/advanced/design-patterns/linked-list",
              {
                type: "category",
                label: "Data Structures",
                items: [
                  "build/smart-contracts/advanced/design-patterns/merkle-tree",
                  "build/smart-contracts/advanced/design-patterns/trie",
                ],
              },
            ],
          },
          "build/smart-contracts/example-contracts",
          {
            type: "category",
            label: "Smart Contract Security",
            link: {
              type: "doc",
              id: "build/smart-contracts/advanced/security/overview",
            },
            items: [
              {
                type: "category",
                label: "Vulnerabilities",
                items: [
                  "build/smart-contracts/advanced/security/vulnerabilities/double-satisfaction",
                  "build/smart-contracts/advanced/security/vulnerabilities/missing-utxo-authentication",
                  "build/smart-contracts/advanced/security/vulnerabilities/time-handling",
                  "build/smart-contracts/advanced/security/vulnerabilities/token-security",
                  "build/smart-contracts/advanced/security/vulnerabilities/unbounded-value",
                  "build/smart-contracts/advanced/security/vulnerabilities/unbounded-datum",
                  "build/smart-contracts/advanced/security/vulnerabilities/unbounded-inputs",
                  "build/smart-contracts/advanced/security/vulnerabilities/other-redeemer",
                  "build/smart-contracts/advanced/security/vulnerabilities/other-token-name",
                  "build/smart-contracts/advanced/security/vulnerabilities/arbitrary-datum",
                  "build/smart-contracts/advanced/security/vulnerabilities/utxo-contention",
                  "build/smart-contracts/advanced/security/vulnerabilities/cheap-spam",
                  "build/smart-contracts/advanced/security/vulnerabilities/insufficient-staking-control",
                  "build/smart-contracts/advanced/security/vulnerabilities/locked-value",
                ],
              },
              "build/smart-contracts/advanced/security/ctf",
            ],
          },
          {
            type: "category",
            label: "Advanced",
            items: [
              "build/smart-contracts/advanced/uplc",
              "build/smart-contracts/advanced/debug-cbor",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Native Tokens",
        link: {
          type: "doc",
          id: "build/native-tokens/overview",
        },
        items: [
          "build/native-tokens/minting",
          "build/native-tokens/minting-nfts",
          "build/native-tokens/authenticated-products",
          {
            type: "category",
            label: "Token Registry",
            items: [
              {
                type: "autogenerated",
                dirName: "build/native-tokens/token-registry",
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Integrate",
        link: {
          type: "doc",
          id: "build/integrate/overview",
        },
        items: [
          {
            type: "category",
            label: "Payments",
            items: [
              {
                type: "category",
                label: "Listening for Payments",
                link: {
                  type: "doc",
                  id: "build/integrate/payments/listening-for-payments/overview",
                },
                items: [
                  "build/integrate/payments/listening-for-payments/point-of-sale",
                  "build/integrate/payments/listening-for-payments/cardano-cli",
                  "build/integrate/payments/listening-for-payments/cardano-wallet",
                ],
              },
              "build/integrate/payments/x402-standard",
            ],
          },
          {
            type: "category",
            label: "Wallet Authentication",
            link: {
              type: "doc",
              id: "build/integrate/wallet-authentication/overview",
            },
            items: [
              "build/integrate/wallet-authentication/mesh",
              {
                type: "category",
                label: "UTXOS Web3 Services",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "build/integrate/wallet-authentication/utxos",
                  },
                ],
              },
              "build/integrate/wallet-authentication/cardano-serialization-lib",
            ],
          },
          {
            type: "category",
            label: "AI Agents",
            link: {
              type: "doc",
              id: "build/integrate/ai-agents/overview",
            },
            items: [
              "build/integrate/ai-agents/masumi",
            ],
          },
          {
            type: "category",
            label: "Oracles",
            link: {
              type: "doc",
              id: "build/integrate/oracles/overview",
            },
            items: [
              "build/integrate/oracles/charli3",
              "build/integrate/oracles/orcfax",
            ],
          },
          "build/integrate/exchange-integrations",
        ],
      },
      {
        type: "category",
        label: "Transaction Metadata",
        link: {
          type: "doc",
          id: "build/transaction-metadata/overview",
        },
        items: [
          {
            type: "category",
            label: "Tutorials",
            items: [
              "build/transaction-metadata/mesh",
              "build/transaction-metadata/how-to-create-a-metadata-transaction-cli",
              "build/transaction-metadata/how-to-create-a-metadata-transaction-wallet",
            ],
          },
          "build/transaction-metadata/retrieving-metadata",
        ],
      },
      {
        type: "category",
        label: "Lessons",
        link: {
          type: "doc",
          id: "build/smart-contracts/lessons-overview",
        },
        items: [
          {
            type: "autogenerated",
            dirName: "build/smart-contracts/lessons",
          },
        ],
      },
      ],
    },
    {
      type: "category",
      label: "Community",
      items: [
      "community/cardano-developer-community",
      "community/funding",
      "community/careers",
      ],
    },
    {
      type: "category",
      label: "Contributing to Developer Portal",
      items: [
      "contribute/portal-contribute",
      "contribute/portal-style-guide",
      {
        type: "link",
        label: "Contributors",
        href: "https://github.com/cardano-foundation/developer-portal/graphs/contributors",
      },
      ],
    },
  ],

  governanceSidebar: [
    {
      type: "category",
      label: "Participate in Governance",
      link: {
        type: "doc",
        id: "governance/overview",
      },
      items: [
      {
        type: "category",
        label: "Cardano Governance",
        link: {
          type: "doc",
          id: "governance/cardano-governance/overview",
        },
        items: [
          "governance/cardano-governance/cardano-governance",
          "governance/cardano-governance/governance-actions",
          "governance/cardano-governance/submitting-governance-actions",
          "governance/cardano-governance/constitutional-committee-guide",
        ],
      },
      ],
    },
    {
      type: "category",
      label: "Contributing to Developer Portal",
      items: [
      "contribute/portal-contribute",
      "contribute/portal-style-guide",
      {
        type: "link",
        label: "Contributors",
        href: "https://github.com/cardano-foundation/developer-portal/graphs/contributors",
      },
      ],
    },
  ],

  networkSidebar: [
    {
      type: "category",
      label: "Operate a Stake Pool",
      link: {
        type: "doc",
        id: "operate-a-stake-pool/overview",
      },
      items: [
      {
        type: "category",
        label: "Basics",
        items: [
          "operate-a-stake-pool/basics/consensus-staking",
          "operate-a-stake-pool/basics/stake-pool-networking",
          "operate-a-stake-pool/basics/hardware-requirements",
          "operate-a-stake-pool/basics/cardano-key-pairs",
        ],
      },
      {
        type: "category",
        label: "Cardano Relay Configuration",
        items: [
          "operate-a-stake-pool/relay-configuration/relay-node-configuration",
          "operate-a-stake-pool/relay-configuration/monitoring-gLiveView",
          "operate-a-stake-pool/relay-configuration/grafana-dashboard-tutorial",
        ],
      },
      {
        type: "category",
        label: "Cardano Block Producer Configuration",
        items: [
          "operate-a-stake-pool/block-producer/generating-wallet-keys",
          "operate-a-stake-pool/block-producer/block-producer-keys",
          "operate-a-stake-pool/block-producer/register-stake-address",
          "operate-a-stake-pool/block-producer/register-stake-pool",
        ],
      },
      {
        type: "category",
        label: "Deployment Scenarios",
        items: [
          "operate-a-stake-pool/deployment-scenarios/hardening-server",
          "operate-a-stake-pool/deployment-scenarios/improve-grafana-security",
          "operate-a-stake-pool/deployment-scenarios/audit-your-node",
        ],
      },
      {
        type: "category",
        label: "Cardano Governance",
        items: [
          "operate-a-stake-pool/governance/on-chain-polls",
        ],
      },
      {
        type: "category",
        label: "Operator Tools",
        items: [
          "operate-a-stake-pool/operator-tools/guild-ops-suite",
          "operate-a-stake-pool/operator-tools/frankenwallet",
        ],
      },
      ],
    },
    {
      type: "category",
      label: "Contributing to Developer Portal",
      items: [
      "contribute/portal-contribute",
      "contribute/portal-style-guide",
      {
        type: "link",
        label: "Contributors",
        href: "https://github.com/cardano-foundation/developer-portal/graphs/contributors",
      },
      ],
    },
  ],
};