name = "cardano-foundation/onboarding-giftcard"
version = "0.0.0"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "The gift card contract from the onboarding Intermediate lectures"

[repository]
user = "cardano-foundation"
project = "developer-portal"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.23"
source = "github"

[config]
