blank_issues_enabled: true
contact_links:
  - name: Contribution guidelines
    url: https://github.com/cardano-foundation/developer-portal/blob/staging/CONTRIBUTING.md
    about: Read the documentation and guidelines before filing an issue.

  - name: Ideas and discussions
    url: https://github.com/cardano-foundation/developer-portal/discussions
    about: Share ideas and proposals or ask open questions.

  - name: Join Intersect
    url: https://members.intersectmbo.org
    about: Register with Intersect to access Discord and other community resources.